### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by Jaguar-515** [iranathan/robloxapi#11]
Code that I attempted to get working:
```python
>>> import robloxapi
>>> rbx = robloxapi.client()
>>> profile = rbx.User.getProfile(1)
```
The error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\robloxapi\User.py", line 36, in getProfile
    status_req = self._request(url='https://www.roblox.com/users/profile/profileheader-json?userId=' + id)
TypeError: can only concatenate str (not "int") to str
```

**Comment by sbhadr** [comment]
That's a type error. When you try to combine two primitives with differing types. 
https://github.com/iranathan/robloxapi/pull/12
