### ISSUE TITLE
NameError: name 'client' is not defined

### ISSUE THREAD

**Issue by xDsquare** [iranathan/robloxapi#4]
I'm getting following error now:
```
import robloxapi
rbx = robloxapi.client()
print(rbx.Auth.login("_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_...))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/robloxapi/Auth.py", line 18, in login
    return client(cookie)
NameError: name 'client' is not defined
```

**Comment by iranathan** [comment]
Sorry, Fixed.
